const defaultServersTypes = {
    DEFAULT_SERVERS_PENDING: 'DEFAULT_SERVERS_PENDING',
    DEFAULT_SERVERS_SUCCESS: 'DEFAULT_SERVERS_SUCCESS',
    DEFAULT_SERVERS_FAILURE: 'DEFAULT_SERVERS_FAILURE'
};

export default defaultServersTypes;