const fetchUserTypes = {
    FETCH_USER_PENDING: 'FETCH_USER_PENDING',
    FETCH_USER_SUCCESS: 'FETCH_USER_SUCCESS',
    FETCH_USER_FAILURE: 'FETCH_USER_FAILURE',
    RESET_USER: 'RESET_USER'
};

export default fetchUserTypes;